### ISSUE TITLE
Card number duplicated 

### ISSUE THREAD

**Issue by DannyFeliz** [developersdo/opensource#38] opened 2017-10-19 08:09 UTC
If you scroll down too fast something happens with the position numbers and appear duplicates
![image](https://user-images.githubusercontent.com/5460365/31759785-88877764-b480-11e7-99ed-292bf5e5ddb0.png)

**Comment by rmariuzzo** [comment] 2017-10-19 12:44
Do you mean duplicate position number? Or duplicate card?

**Comment by iCueto** [comment] 2017-10-19 15:40
He means that the position numbers is duplicate... :)

**Comment by Hekotoru** [comment] 2017-10-19 19:40
And the star number too.

**Comment by rmariuzzo** [comment] 2017-10-19 20:32
It was intentional. Popular repositories are sorted by stargazers. However, two or more repositories can have same amount of stargazers. That's the reason I'm giving the same position.

What do you all think?

**Comment by Hekotoru** [comment] 2017-10-20 13:43
It's nice to have it in the same position but in that way we don't have a validation to create an unique position number. So my suggestion is to remove the card number and give priority to the search bar.

**Comment by mecm1993** [comment] 2017-10-20 13:49
The cause of the weird behavior of issue [#34](https://github.com/developersdo/opensource/issues/34) is because of the same amount of stargazers between repos. However, in my opinion this is a list of the most popular, trending or newest repos from our community.

Therefore, duplication of position should not be allowed, if there are two or more repos with the same amount of stargazers, then the amount of watchers or forks should come up to make the difference between positions.

**Comment by rmariuzzo** [comment] 2017-10-20 14:15
@hekotoru the search in both the repos and devs is a must have. We have to creat an issue for that.

@mecm1993 I understand your point on the #34. Even if we use more fields we should deal properly with repos that can have the same popularity.

Personally, I think the same position number due to the same amount of stargazers can be confusing. With that I mind it would be better to use more fields as suggested by @mecm1993 and finally sitting by their repo name and done. What do you all think?

**Comment by rmariuzzo** [comment] 2017-10-20 16:37
This will be handled at #40. I will close this.

**Closed by rmariuzzo** 2017-10-20 16:37 UTC
Labels: discussion
